name: AWS EKS Deployment

on:
  push:
    branches:
      - main #Add your branch
env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: Azhar-EKS #Add your Cluster Name
  #ECR_REPOSITORY_NAME: Repo Name #Add your Repo Name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        env:
          EKS_CLUSTER_ROLE_ARN: arn:aws:iam::678878256416:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS #user arn
        run: |
          aws eks update-kubeconfig --name Azhar-EKS --region us-east-1 --role-arn $EKS_CLUSTER_ROLE_ARN
          kubectl get ns


      #- name: Login to Amazon ECR
      #  id: login-ecr
      #  uses: aws-actions/amazon-ecr-login@v1

      #- name: Build, tag, and push image to Amazon ECR
      #  env:
      #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #    ECR_REPOSITORY: Repo Name
      #    IMAGE_TAG: Latest

      #  run: |
      #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend/
      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS
        run: |
          kubectl apply -f Deployment\sample-image.yaml
